# Training Configuration
data:
  batch_size: 16
  train_split: 0.8
  num_workers: 2
  
model:
  architecture: 'resnet18'
  pretrained: true
  dropout: 0.2

training:
  epochs: 40
  learning_rate: 0.0001
  weight_decay: 0.0001
  device: 'cpu'  # or 'cuda' if available

augmentation:
  enabled: true
  horizontal_flip: 0.5
  color_jitter: 0.2
